import { IDBFactory } from 'fake-indexeddb'
import { SoundBankLoader } from 'spessasynth_core'
import { describe, expect, it } from 'vitest'

import { estimateRenderBytes } from '../export/audioRender'
import {
  sampleSoundBankBytes,
  sampleSoundBankDigest,
  sampleSoundBankPreset,
} from '../test/fixtures/compositions'
import { soundBankContainerKind } from './soundfontProbe'
import { SoundBankStore } from './soundbankStore'

/**
 * Release budgets for sound-bank initialization and SoundFont render memory.
 *
 * The MG-21 contract named both, and the packet closed without either because
 * there was no bank to measure. `spessasynth_core` can generate one, so these
 * are now measured rather than deferred.
 *
 * What is measured here is the part that runs on the main thread: container
 * recognition, digest, vault write, and bank parsing into presets. Worklet
 * startup and voice rendering need a real AudioWorklet and belong to the
 * browser suite, which jsdom cannot host.
 */

let databaseCounter = 0
const freshVault = () =>
  new SoundBankStore({
    indexedDB: new IDBFactory(),
    databaseName: `bank-bench-${(databaseCounter += 1)}`,
  })

describe('sound-bank initialization budget', () => {
  it('recognizes the container without parsing the whole bank', () => {
    const bytes = sampleSoundBankBytes()
    // The container check reads a 12-byte header, so it stays constant no
    // matter how large the bank is. That is what makes rejecting a wrong file
    // cheap enough to do before any of the expensive work below.
    expect(soundBankContainerKind(bytes)).toBe('soundfont')
    expect(soundBankContainerKind(new ArrayBuffer(4))).toBeUndefined()
  })

  it('parses the bank into its presets', () => {
    const loaded = SoundBankLoader.fromArrayBuffer(sampleSoundBankBytes())

    expect(loaded.presets.length).toBeGreaterThan(0)
    expect(loaded.presets[0].name).toBe(sampleSoundBankPreset.name)
    expect(loaded.presets[0].program).toBe(sampleSoundBankPreset.program)
    expect(loaded.instruments.length).toBeGreaterThan(0)
    expect(loaded.samples.length).toBeGreaterThan(0)
  })

  it('imports into an empty vault and reads back byte-identical', async () => {
    const vault = freshVault()
    const bytes = sampleSoundBankBytes()
    const digest = await sampleSoundBankDigest()

    const imported = await vault.importBank({
      bytes,
      name: 'Sample Saw Bank',
      format: 'sf2',
      license: 'Apache-2.0',
      attribution: 'Generated by spessasynth_core',
    })

    expect(imported.created).toBe(true)
    expect(imported.metadata.digest).toBe(digest)
    expect(imported.metadata.byteLength).toBe(bytes.byteLength)

    const stored = await vault.get(digest)
    expect(new Uint8Array(stored!.bytes)).toEqual(new Uint8Array(bytes))
  })

  it('re-importing the same bank stores nothing new', async () => {
    const vault = freshVault()
    const bank = {
      bytes: sampleSoundBankBytes(),
      name: 'Sample Saw Bank',
      format: 'sf2' as const,
      license: 'Apache-2.0',
    }

    expect((await vault.importBank(bank)).created).toBe(true)
    // Content-addressed storage: the second import is a digest comparison, not
    // another write, so repeated imports stay cheap and cannot duplicate.
    expect((await vault.importBank(bank)).created).toBe(false)
    expect(await vault.list()).toHaveLength(1)
  })

  it('holds the checked-in size budget for the generated bank', () => {
    // 890 bytes on spessasynth_core 4.3.x. This is a budget on the fixture,
    // not on the library: if it moves, the numbers in the benchmarks and in
    // docs/examples/BENCHMARKS.md need rechecking rather than silently drifting.
    expect(sampleSoundBankBytes().byteLength).toBe(890)
  })
})

describe('SoundFont render memory budget', () => {
  it('adds the resident bank to the render estimate', async () => {
    const bytes = sampleSoundBankBytes()
    const renderSeconds = 10

    // Rendering a SoundFont costs the same buffers as a native render plus the
    // bank, which stays resident for the whole render.
    const nativeBytes = estimateRenderBytes(renderSeconds, 44_100, 2, 16)
    const withBank = nativeBytes + bytes.byteLength

    expect(withBank).toBeGreaterThan(nativeBytes)
    // For any realistic bank the buffers dominate; this one is negligible.
    expect(bytes.byteLength / nativeBytes).toBeLessThan(0.001)

    // A 30 MB General MIDI bank is the case worth stating: still under the
    // render buffers for a ten-second stereo render, so a bank never turns a
    // render from feasible into infeasible on its own.
    const generalMidiBytes = 30 * 1_048_576
    expect(generalMidiBytes).toBeLessThan(nativeBytes * 8)
  })

  it('keeps the vault copy separate from the render copy', async () => {
    const vault = freshVault()
    const bytes = sampleSoundBankBytes()
    await vault.importBank({
      bytes,
      name: 'Sample Saw Bank',
      format: 'sf2',
      license: 'Apache-2.0',
    })

    const first = await vault.get(await sampleSoundBankDigest())
    const second = await vault.get(await sampleSoundBankDigest())

    // Each read hands back its own buffer. That costs a copy per read, and it
    // is why a render can transfer its bytes to a worklet without the vault's
    // stored copy being detached underneath it.
    expect(first!.bytes).not.toBe(second!.bytes)
    expect(new Uint8Array(first!.bytes)).toEqual(new Uint8Array(second!.bytes))
  })
})
