import {
  compositionVersion,
  type Composition,
} from './composition'

export const defaultComposition = {
  version: compositionVersion,
  id: 'simple-ring-crossing',
  name: 'Simple Ring Crossing',
  space: {
    center: { x: 0, y: 0 },
    scale: 1,
  },
  transport: {
    tempoBpm: 120,
    meter: { beatsPerBar: 4, beatUnit: 4 },
    loop: { startBeat: 0, lengthBeats: 4 },
  },
  wheels: [
    {
      id: 'wheel-1',
      name: 'Wheel 1',
      enabled: true,
      center: { x: 0, y: 0 },
      rate: { cycles: 1, beats: 4 },
      phase: 0,
      direction: 'forward',
      motion: {
        kind: 'spirogram',
        fixedRadius: 180,
        movingRadius: 65,
        rotation: 'inside',
      },
      heads: [
        {
          id: 'head-1',
          name: 'Head 1',
          enabled: true,
          phaseOffset: 0,
          offset: { x: 0, y: 0 },
          attachment: { kind: 'spirogram', penOffset: 95 },
          trace: {
            visible: true,
            color: '#6fd6c2',
            lineWidth: 2,
            opacity: 0.9,
            mode: 'animated',
            historySeconds: 8,
          },
        },
      ],
    },
  ],
  fields: [
    {
      id: 'field-rings',
      name: 'Rings',
      enabled: true,
      kind: 'rings',
      center: { x: 0, y: 0 },
      boundaries: [
        {
          id: 'ring-inner',
          name: 'Inner Ring',
          enabled: true,
          index: 0,
          kind: 'ring',
          radius: 90,
        },
        {
          id: 'ring-outer',
          name: 'Outer Ring',
          enabled: true,
          index: 1,
          kind: 'ring',
          radius: 180,
        },
      ],
    },
    {
      id: 'field-spokes',
      name: 'Spokes',
      enabled: true,
      kind: 'spokes',
      center: { x: 0, y: 0 },
      rotation: 0,
      boundaries: [
        {
          id: 'spoke-east',
          name: 'East Spoke',
          enabled: true,
          index: 0,
          kind: 'spoke',
          angle: 0,
        },
        {
          id: 'spoke-north',
          name: 'North Spoke',
          enabled: true,
          index: 1,
          kind: 'spoke',
          angle: Math.PI / 2,
        },
      ],
    },
  ],
  soundBanks: [],
  instruments: [
    {
      id: 'instrument-1',
      name: 'Native Synth',
      kind: 'native-synth',
      gain: 0.5,
      pan: 0,
      waveform: 'triangle',
      envelope: {
        attackSeconds: 0.01,
        decaySeconds: 0.08,
        sustain: 0.7,
        releaseSeconds: 0.15,
      },
    },
  ],
  parts: [
    {
      id: 'part-1',
      name: 'Boundary Melody',
      enabled: true,
      kind: 'note',
      encounterQuery: {
        kinds: ['boundary-crossing'],
        wheelIds: ['wheel-1'],
        headIds: ['head-1'],
        fieldIds: [],
        boundaryIds: [],
        directions: [],
        minStrength: 0,
      },
      instrumentId: 'instrument-1',
      onset: { kind: 'encounter-time' },
      pitch: {
        kind: 'boundary-degree',
        root: 48,
        scale: 'pentatonic-minor',
        octaves: 3,
      },
      velocity: {
        kind: 'encounter-strength',
        min: 48,
        max: 118,
        gamma: 1,
      },
      duration: { kind: 'fixed', beats: 0.25 },
      quantize: { gridBeats: 0.25, strength: 0.75 },
    },
  ],
} satisfies Composition
